CREATE TABLE UserLoginHistory (
    id INT PRIMARY KEY IDENTITY(1,1),
    user_id INT NOT NULL,
    login_time DATETIME DEFAULT GETDATE() NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);