ALTER TABLE Meal
ALTER COLUMN carbohydrates DECIMAL(7,2);

ALTER TABLE Meal
ALTER COLUMN protein DECIMAL(7,2);

ALTER TABLE Meal
ALTER COLUMN fat DECIMAL(7,2);

ALTER TABLE Meal
ALTER COLUMN calories DECIMAL(7,2);